name: attrition-esn-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - shap=0.45.0
  - scikit-learn
  - imbalanced-learn
  - xgboost=2.0.3
  - joblib
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - python-dotenv
  - jupyterlab
  - ipython
  - black
