jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install test & coverage tools
        run: pip install pytest coverage
      - name: Run tests with coverage
        run: coverage run -m pytest tests/
      - name: Generate coverage HTML report
        run: coverage html
      - name: Upload HTML coverage
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./htmlcov

  # Job séparé pour le déploiement Pages
  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-and-test # trigger après le job test
    steps:
      - uses: actions/deploy-pages@v4
